### ISSUE TITLE
Uncaught SyntaxError: Unexpected token \

### ISSUE THREAD

**Issue by sandroasatiani** [sveale/remote-edit#111] opened 2015-08-07 09:08 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.14

### Stack Trace

Uncaught SyntaxError: Unexpected token \

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.5%22%2C%22shellLoadTime%22%3A276%2C%22initialPaths%22%3A%5B%5D%7D:1

SyntaxError: Unexpected token \
    at Object.parse (native)
    at /Users/sandroasatiani/.atom/packages/remote-edit/lib/model/inter-process-data-watcher.coffee:93:54
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

### Commands

```
     -0:00.6.0 remote-edit:show-open-files (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/sandroasatiani/Documents/_GitHub"
  },
  "remote-edit": {}
}
```

### Installed Packages

```coffee
# User
remote-edit, v1.8.14

# Dev
No dev packages
```

**Comment by sveale** [comment] 2015-08-07 09:09
Duplicate of #108

**Closed by sveale** 2015-08-07 09:09 UTC
