### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by kengone** [sveale/remote-edit#137] opened 2015-10-30 00:27 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [remote-edit](https://github.com/sveale/remote-edit) package, v1.8.21

### Stack Trace

Failed to load the remote-edit package

```
At TextEditor.registerDeserializer is not a function

TypeError: TextEditor.registerDeserializer is not a function
  at /Users/keng/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:26:16
  at Object.<anonymous> (/Users/keng/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:253:5)
  at Object.<anonymous> (/Users/keng/.atom/packages/remote-edit/lib/model/remote-edit-editor.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/keng/.atom/packages/remote-edit/lib/main.coffee:2:20)
  at Object.<anonymous> (/Users/keng/.atom/packages/remote-edit/lib/main.coffee:2:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:473:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -5:28.9.0 remote-ftp:disconnect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:13.4.0 pane:show-item-7 (div.offline)
  6x -5:10.3.0 tree-view:toggle (div.offline)
     -4:28.1.0 application:add-project-folder (atom-pane.pane.active)
  8x -3:50.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:13.7.0 dev-live-reload:reload-all (ul.list-inline.tab-bar.inset-panel)
     -2:00.7.0 tree-view:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:51.9.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
     -1:40.8.0 pane:split-down (div.item-views)
     -1:34.6.0 pane:close (div.item-views)
     -1:13.8.0 command-palette:toggle (atom-pane.pane.active)
     -1:07.8.0 settings-view:open (atom-pane.pane.active)
  4x -0:32.9.0 core:copy (table.package-keymap-table.table.native-key-bindings.text)
     -0:28.8.0 command-palette:toggle (table.package-keymap-table.table.native-key-bindings.text)
     -0:27.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
 31x -0:25 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.8
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
color-picker, v2.0.13
html-entities, v0.4.0
html-id-class-snippets, v1.4.1
language-b-html, v1.0.0
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by matthewknecht** [comment] 2015-10-30 13:41
Just reinstall Atom with this build:
https://github.com/atom/atom/releases/tag/v1.0.19
You keep all your packages and themes, so don't worry.

**Comment by sveale** [comment] 2015-11-01 20:31
Duplicate of #129

**Closed by sveale** 2015-11-01 20:31 UTC
